package com.ecrinlabs.repo2play;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import org.json.*;
public class MainActivity extends Activity{
 int BG=Color.rgb(9,11,16),CARD=Color.rgb(20,23,31),TXT=Color.rgb(242,245,248),MUT=Color.rgb(150,158,171),GREEN=Color.rgb(167,244,50);
 EditText token,engine,target,branch; TextView status; Button n,u,build; String mode="NEW"; android.content.SharedPreferences prefs;
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("r2p",0);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);ScrollView sv=new ScrollView(this);sv.setBackgroundColor(BG);LinearLayout p=col();p.setPadding(d(20),d(25),d(20),d(35));sv.addView(p);
 p.addView(t("REPO2PLAY",29,TXT,true));TextView s=t("GitHub → Android → Play Store",14,MUT,false);s.setPadding(0,d(4),0,d(22));p.addView(s);
 LinearLayout auth=card();p.addView(auth);auth.addView(label("GITHUB PERSONAL ACCESS TOKEN"));token=input("github_pat_... / ghp_...");token.setInputType(0x00000081);token.setText(prefs.getString("token",""));auth.addView(token,fp());Button save=button("CONNECT & SAVE TOKEN",false);auth.addView(save,bp());save.setOnClickListener(v->connect());
 LinearLayout c=card();LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,d(14),0,0);p.addView(c,cp);
 c.addView(label("ENGINE REPOSITORY"));engine=input("owner/Repo2Play");engine.setText(prefs.getString("engine",""));c.addView(engine,fp());c.addView(space(12));
 c.addView(label("TARGET ANDROID REPOSITORY"));target=input("owner/repository");c.addView(target,fp());c.addView(space(12));c.addView(label("TARGET BRANCH"));branch=input("main");branch.setText("main");c.addView(branch,fp());c.addView(space(16));c.addView(label("BUILD TYPE"));
 LinearLayout modes=new LinearLayout(this);n=modeBtn("NEW",true);u=modeBtn("UPDATE",false);modes.addView(n,new LinearLayout.LayoutParams(0,d(48),1));LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(0,d(48),1);up.setMargins(d(8),0,0,0);modes.addView(u,up);c.addView(modes);n.setOnClickListener(v->setMode("NEW"));u.setOnClickListener(v->setMode("UPDATE"));
 build=button("BUILD APP",true);c.addView(build,bp());build.setOnClickListener(v->dispatch());
 LinearLayout r=card();LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,d(14),0,0);p.addView(r,rp);r.addView(label("BUILD STATUS"));status=t("Ready",14,TXT,false);status.setPadding(0,d(6),0,0);status.setTextIsSelectable(true);r.addView(status);
 setContentView(sv);}
 void connect(){String tok=token.getText().toString().trim();if(tok.length()<10){token.setError("Token gerekli");return;}setStatus("Connecting GitHub…");new Thread(()->{try{JSONObject me=get("https://api.github.com/user",tok);String login=me.optString("login");runOnUiThread(()->{prefs.edit().putString("token",tok).apply();setStatus("✓ Connected as "+login+"\nToken saved on this device.");});}catch(Exception e){err(e);}}).start();}
 void dispatch(){String tok=token.getText().toString().trim(),eng=norm(engine.getText().toString()),tar=norm(target.getText().toString()),br=branch.getText().toString().trim();if(tok.length()<10){token.setError("Token gerekli");return;}if(eng==null){engine.setError("owner/repository");return;}if(tar==null){target.setError("owner/repository");return;}if(br.isEmpty()){branch.setError("Branch gerekli");return;}prefs.edit().putString("token",tok).putString("engine",eng).apply();build.setEnabled(false);setStatus("Starting "+mode+" build…");new Thread(()->{try{
 String url="https://api.github.com/repos/"+eng+"/actions/workflows/repo2play.yml/dispatches";JSONObject body=new JSONObject();body.put("ref","v11-production");JSONObject in=new JSONObject();in.put("repository",tar);in.put("branch",br);in.put("build_mode",mode);body.put("inputs",in);JSONObject res=post(url,tok,body.toString());long id=res.optLong("workflow_run_id",0);if(id==0)throw new Exception("GitHub did not return workflow_run_id. Response: "+res);poll(eng,tok,id);
 }catch(Exception e){err(e);runOnUiThread(()->build.setEnabled(true));}}).start();}
 void poll(String eng,String tok,long id)throws Exception{String run="https://api.github.com/repos/"+eng+"/actions/runs/"+id;while(true){JSONObject j=get(run,tok);String st=j.optString("status"),con=j.optString("conclusion");runOnUiThread(()->setStatus("Run #"+id+"\nStatus: "+st+(con.isEmpty()?"":"\nResult: "+con)));if("completed".equals(st)){if(!"success".equals(con))throw new Exception("Build finished: "+con+"\n"+j.optString("html_url"));break;}Thread.sleep(5000);}
 JSONObject a=get("https://api.github.com/repos/"+eng+"/actions/runs/"+id+"/artifacts",tok);JSONArray arr=a.optJSONArray("artifacts");if(arr==null||arr.length()==0)throw new Exception("Build succeeded but artifact was not found.");JSONObject art=arr.getJSONObject(0);long aid=art.getLong("id");String name=art.optString("name","Repo2Play-Result");String dl="https://api.github.com/repos/"+eng+"/actions/artifacts/"+aid+"/zip";runOnUiThread(()->{setStatus("✓ BUILD COMPLETE\n"+name+"\n\nTap DOWNLOAD RESULT for APK / AAB / JKS / reports.");showDownload(dl,tok,name+".zip");});}
 void showDownload(String url,String tok,String name){build.setText("DOWNLOAD RESULT");build.setEnabled(true);build.setOnClickListener(v->download(url,tok,name));}
 void download(String url,String tok,String name){setStatus("Downloading result…");build.setEnabled(false);new Thread(()->{try{HttpURLConnection c=req(url,tok);c.setInstanceFollowRedirects(false);int code=c.getResponseCode();String loc=c.getHeaderField("Location");c.disconnect();if(code/100==3&&loc!=null){DownloadManager.Request r=new DownloadManager.Request(Uri.parse(loc));r.setTitle(name);r.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS,name);r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(r);runOnUiThread(()->{setStatus("✓ Download started\nDownloads/"+name);build.setText("BUILD APP");build.setEnabled(true);build.setOnClickListener(v->dispatch());});}else throw new Exception("Artifact download redirect failed: HTTP "+code);}catch(Exception e){err(e);runOnUiThread(()->build.setEnabled(true));}}).start();}
 JSONObject get(String u,String tok)throws Exception{HttpURLConnection c=req(u,tok);return parse(c);}
 JSONObject post(String u,String tok,String body)throws Exception{HttpURLConnection c=req(u,tok);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}return parse(c);}
 HttpURLConnection req(String u,String tok)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestProperty("Accept","application/vnd.github+json");c.setRequestProperty("Authorization","Bearer "+tok);c.setRequestProperty("X-GitHub-Api-Version","2026-03-10");c.setRequestProperty("User-Agent","Repo2Play-Android");return c;}
 JSONObject parse(HttpURLConnection c)throws Exception{int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String x=read(in);c.disconnect();if(code<200||code>=300)throw new Exception("GitHub HTTP "+code+"\n"+x);return x.trim().isEmpty()?new JSONObject():new JSONObject(x);}
 String read(InputStream in)throws Exception{if(in==null)return"";BufferedReader b=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l);return s.toString();}
 String norm(String x){x=x.trim().replaceFirst("^https?://github\\.com/","").replaceFirst("\\.git$","").replaceAll("/+$","");return x.matches("[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+")?x:null;}
 void err(Exception e){runOnUiThread(()->setStatus("✕ "+e.getMessage()));}
 void setStatus(String x){status.setText(x);}
 void setMode(String x){mode=x;boolean a=x.equals("NEW");n.setTextColor(a?Color.BLACK:TXT);n.setBackground(round(a?GREEN:Color.rgb(35,39,49),12));u.setTextColor(!a?Color.BLACK:TXT);u.setBackground(round(!a?GREEN:Color.rgb(35,39,49),12));}
 LinearLayout card(){LinearLayout l=col();l.setPadding(d(16),d(16),d(16),d(16));l.setBackground(round(CARD,16));return l;}LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}TextView label(String x){TextView v=t(x,11,MUT,true);v.setPadding(0,0,0,d(6));return v;}TextView t(String x,int z,int c,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,1);return v;}EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.rgb(100,108,120));e.setTextColor(TXT);e.setSingleLine();e.setPadding(d(12),0,d(12),0);e.setBackground(round(Color.rgb(29,33,42),11));return e;}Button button(String x,boolean g){Button b=new Button(this);b.setText(x);b.setTypeface(null,1);b.setTextColor(g?Color.BLACK:TXT);b.setBackground(round(g?GREEN:Color.rgb(35,39,49),12));return b;}Button modeBtn(String x,boolean a){return button(x,a);}LinearLayout.LayoutParams fp(){return new LinearLayout.LayoutParams(-1,d(50));}LinearLayout.LayoutParams bp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,d(54));p.setMargins(0,d(15),0,0);return p;}View space(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,d(h)));return v;}GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d(r));return g;}int d(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
}